### ISSUE TITLE
assert!( modulus - ONE < MAX / (modulus - ONE) )  does not trigger when it should

### ISSUE THREAD

**Issue by xiegeo** [pwoolcoc/mod_exp-rs#1]
The check for overflow does nothing since if the LHS overflowed, it would be smaller than MAX.

I think assert!( modulus - ONE < MAX / (modulus - ONE) ) should work, or use [checked_mul](https://rust-num.github.io/num/num_traits/ops/checked/trait.CheckedMul.html).

**Comment by pwoolcoc** [comment]
Good catch, thanks for the bug report!
